language: php

php:
  - "7.0"
  - "7.1"

env:
  - CONTAO_VERSION=~3.5.0

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer config repositories.member-logo vcs https://github.com/richardhj/contao-member_logo
  - travis_retry composer config repositories.upload-preview-field vcs https://github.com/richardhj/contao-upload_preview_field
  - travis_retry composer config repositories.dcg-single-model vcs https://github.com/richardhj/dc-general-single-model
  - travis_retry composer config repositories.member-logo vcs https://github.com/richardhj/contao-member_logo
  - travis_retry composer require contao/core $CONTAO_VERSION --no-update
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going
