services:
    richardhj.ferienpass.metamodels.attribute.age.factory:
        class: Richardhj\ContaoFerienpassBundle\MetaModels\Attribute\Age\AttributeTypeFactory
        arguments:
            - '@database_connection'
        tags:
            - { name: metamodels.attribute_factory }
    richardhj.ferienpass.metamodels.attribute.offer_date.factory:
        class: Richardhj\ContaoFerienpassBundle\MetaModels\Attribute\OfferDate\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@event_dispatcher'
        tags:
            - { name: metamodels.attribute_factory }
    richardhj.ferienpass.metamodels.filter.age.factory:
        class: Richardhj\ContaoFerienpassBundle\MetaModels\FilterSetting\AgeFilterSettingTypeFactory
        tags:
            - { name: metamodels.filter_factory }
    richardhj.ferienpass.metamodels.filter.attendance_available.factory:
        class: Richardhj\ContaoFerienpassBundle\MetaModels\FilterSetting\AttendanceAvailableFilterSettingTypeFactory
        tags:
            - { name: metamodels.filter_factory }
    richardhj.ferienpass.metamodels.filter.from_to_offer_date.factory:
        class: Richardhj\ContaoFerienpassBundle\MetaModels\FilterSetting\FromToOfferDateFilterSettingTypeFactory
        tags:
            - { name: metamodels.filter_factory }
    richardhj.ferienpass.metamodels.filter.age.filter_setting_renderer_listener:
        class: Richardhj\ContaoFerienpassBundle\MetaModels\EventListener\AgeFilterSettingTypeRendererListener
        arguments:
            - "@metamodels.filter_setting_factory"
            - "@event_dispatcher"
            - "@metamodels.assets.icon_builder"
            - "@cca.dc-general.scope-matcher"
        tags:
            - {
                name: kernel.event_listener,
                event: 'dc-general.view.contao2backend.model-to-label',
                method: modelToLabel
              }
    richardhj.ferienpass.metamodels.filter.attendance_available.filter_setting_renderer_listener:
        class: Richardhj\ContaoFerienpassBundle\MetaModels\EventListener\AttendanceAvailableFilterSettingTypeRendererListener
        arguments:
            - "@metamodels.filter_setting_factory"
            - "@event_dispatcher"
            - "@metamodels.assets.icon_builder"
            - "@cca.dc-general.scope-matcher"
        tags:
            - {
                name: kernel.event_listener,
                event: 'dc-general.view.contao2backend.model-to-label',
                method: modelToLabel
              }


    richardhj.ferienpass.listener.user_application.add_attendance_status_confirmation:
        class: Richardhj\ContaoFerienpassBundle\EventListener\UserApplication\AddAttendanceStatusConfirmationListener
        tags:
            - { name: kernel.event_listener, event: 'model.post-save' }

    richardhj.ferienpass.listener.user_application.build_participant_options.disable_already_attending:
        class: Richardhj\ContaoFerienpassBundle\EventListener\UserApplication\BuildParticipantOptions\DisableAlreadyAttendingParticipantsListener
        tags:
            - { name: kernel.event_listener, event: 'richardhj.ferienpass.user-application.build-participant-options' }

    richardhj.ferienpass.listener.user_application.build_participant_options.disable_double_booking:
        class: Richardhj\ContaoFerienpassBundle\EventListener\UserApplication\BuildParticipantOptions\DisableDoubleBookingParticipantsListener
        tags:
            - { name: kernel.event_listener, event: 'richardhj.ferienpass.user-application.build-participant-options' }

    richardhj.ferienpass.listener.user_application.build_participant_options.disable_wrong_age:
        class: Richardhj\ContaoFerienpassBundle\EventListener\UserApplication\BuildParticipantOptions\DisableWrongeAgeParticipantsListener
        tags:
            - { name: kernel.event_listener, event: 'richardhj.ferienpass.user-application.build-participant-options' }
