richardhj.ferienpass.redirect_short_url:
    path: /{itemId}
    defaults:
        _scope: frontend
        _controller: richardhj.ferienpass.controller.redirect_short_url
    requirements:
        itemId: '\d+'

richardhj.ferienpass.export_attendances:
    path: /share/anmeldungen-ferienpass-{memberId}-{token}.{_format}
    defaults:
        _scope: frontend
        _token_check: false
        _controller: richardhj.ferienpass.controller.export_attendances
        _format: ics
    requirements:
        memberId: '\d+'

richardhj.ferienpass.dropbox_webhook:
    path: /ferienpass-dropbox-webhook
    defaults:
        _scope: frontend
        _token_check: false
        _controller: richardhj.ferienpass.controller.dropbox_webhook

richardhj.ferienpass.backend.erase_personal_data:
    path: /contao/ferienpass/erase_personal_data
    defaults:
        _scope: backend
        _token_check: true
        _controller: richardhj.ferienpass.controller.backend.erase_personal_data

richardhj.ferienpass.backend.send_attendances_overview:
    path: /contao/ferienpass/send_attendances_overview
    defaults:
        _scope: backend
        _token_check: true
        _controller: richardhj.ferienpass.controller.backend.send_attendances_overview

richardhj.ferienpass.code_validate:
    path: /ferienpass-code-validate
    defaults:
        _scope: frontend
        _controller: richardhj.ferienpass.controller.code_validate
