richardhj.ferienpass.redirect_short_url:
    path: /{item}
    defaults:
        _scope: frontend
        _token_check: true
        _controller: richardhj.ferienpass.controller.redirect_short_url
    requirements:
        page: '\d+'
