services:
    richardhj.ferienpass.controller.redirect_short_url:
        class: Richardhj\ContaoFerienpassBundle\Controller\Frontend\RedirectShortUrl
        arguments:
          - '@metamodels.factory'
          - '@event_dispatcher'

    richardhj.ferienpass.controller.dropbox_webhook:
        class: Richardhj\ContaoFerienpassBundle\Controller\Backend\DropboxWebhook

    richardhj.ferienpass.application_system.firstcome:
        class: Richardhj\ContaoFerienpassBundle\ApplicationSystem\FirstCome
        lazy: true

    richardhj.ferienpass.application_system.lot:
        class: Richardhj\ContaoFerienpassBundle\ApplicationSystem\Lot
        lazy: true

    richardhj.ferienpass.application_system:
        factory: ['Richardhj\ContaoFerienpassBundle\ApplicationSystem\ApplicationSystemFactory', create]
