services:
    richardhj.ferienpass.controller.redirect_short_url:
        class: Richardhj\ContaoFerienpassBundle\Controller\Frontend\RedirectShortUrl
        arguments:
          - '@metamodels.factory'
          - '@event_dispatcher'

    richardhj.ferienpass.controller.dropbox_webhook:
        class: Richardhj\ContaoFerienpassBundle\Controller\Backend\DropboxWebhook

    richardhj.ferienpass.application_system.firstcome:
        class: Richardhj\ContaoFerienpassBundle\ApplicationSystem\FirstCome
        factory: ['Richardhj\ContaoFerienpassBundle\ApplicationSystem\ApplicationSystemFactory', createFirstCome]
        lazy: true

    richardhj.ferienpass.application_system.lot:
        class: Richardhj\ContaoFerienpassBundle\ApplicationSystem\Lot
        factory: ['Richardhj\ContaoFerienpassBundle\ApplicationSystem\ApplicationSystemFactory', createLot]
        lazy: true

    richardhj.ferienpass.application_system:
        class: Richardhj\ContaoFerienpassBundle\ApplicationSystem\AbstractApplicationSystem
        factory: ['Richardhj\ContaoFerienpassBundle\ApplicationSystem\ApplicationSystemFactory', create]

    richardhj.ferienpass.model.participant:
        class: Richardhj\ContaoFerienpassBundle\Model\Participant
        arguments:
            - '@metamodels.factory'

    richardhj.ferienpass.model.offer:
        class: Richardhj\ContaoFerienpassBundle\Model\Offer
        arguments:
            - '@metamodels.factory'

    richardhj.ferienpass.pass_releases:
        class: Richardhj\ContaoFerienpassBundle\Util\PassReleases
        arguments:
            - '@metamodels.factory'
            - '@database_connection'

    richardhj.ferienpass.dropbox_client:
        class: Spatie\Dropbox\Client
        arguments:
            - "authorization-token"
